# Farmers Market Platform - Production Dockerfile
# Optimized for Next.js 15 with Prisma and PostgreSQL

# Build stage
FROM node:20-alpine3.20 AS builder

# Set working directory
WORKDIR /app

# Install dependencies needed for Prisma
RUN apk add --no-cache libc6-compat openssl

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install ALL dependencies (including dev dependencies needed for build)
RUN npm ci && \
  npm cache clean --force

# Copy application code
COPY . .

# Prisma Client is already generated by postinstall hook during npm ci
# Just verify it exists, if not generate it
RUN test -d node_modules/.prisma/client || npx prisma generate

# Build Next.js application
# Disable Sentry, telemetry, and validation for Docker build
ENV NEXT_TELEMETRY_DISABLED=1
ENV SENTRY_IGNORE_API_RESOLUTION_ERROR=1
ENV SKIP_ENV_VALIDATION=1
ENV NODE_ENV=production
# Sentry will automatically skip upload when auth token is not provided
RUN npm run build 2>&1 | tee /tmp/build.log || (echo "===== BUILD FAILED =====" && cat /tmp/build.log && exit 1)

# Production stage
FROM node:20-alpine3.20 AS runner

WORKDIR /app

# Install production dependencies, OpenSSL for Prisma, and create non-root user
RUN apk add --no-cache openssl && \
  addgroup --system --gid 1001 nodejs && \
  adduser --system --uid 1001 nextjs

# Copy necessary files for Next.js to run
COPY --from=builder --chown=nextjs:nodejs /app/next.config.mjs ./
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 3000

ENV PORT=3000
ENV NODE_ENV=production
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD node -e "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start application with Next.js start
CMD ["npx", "next", "start"]
