import { PrismaPg } from "@prisma/adapter-pg";
import {
  CropFamily,
  PrismaClient,
  ProductCategory,
  Season,
} from "@prisma/client";
import { Pool } from "pg";

// Load environment variables - load .env first, then .env.local (override)
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env") });
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

// Validate DATABASE_URL is set
if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL is not set in environment variables");
}

console.log(
  "🔗 Connecting to database:",
  process.env.DATABASE_URL.replace(/:[^:]*@/, ":****@"),
);

// Initialize PostgreSQL pool and Prisma Client with adapter (Prisma v7 requirement)
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

/**
 * Comprehensive Crop Database Seed
 * Contains 50+ common crops with complete agricultural data
 */

const crops = [
  // VEGETABLES - Leafy Greens
  {
    name: "Lettuce",
    scientificName: "Lactuca sativa",
    commonNames: ["Garden Lettuce", "Leaf Lettuce"],
    category: ProductCategory.VEGETABLES,
    cropType: "LEAFY",
    cropFamily: CropFamily.ASTERACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "PARTIAL_SHADE",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 45, max: 60 },
    plantingDepth: 0.25,
    spacing: { rows: 12, plants: 8 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 12000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.5,
    organicPremium: 1.4,
    inputCostPerAcre: 2500,
    laborHoursPerAcre: 120,
    storageLife: 7,
    priceVolatility: 0.25,
    peakSeason: "Spring, Fall",
    companionPlants: ["Carrots", "Radishes", "Strawberries", "Cucumbers"],
    antagonistPlants: ["Celery", "Cabbage", "Cress", "Parsley"],
    commonPests: ["Aphids", "Slugs", "Cutworms", "Leafminers"],
    commonDiseases: ["Downy Mildew", "Bottom Rot", "Tipburn"],
    nutritionalInfo: {
      calories: 15,
      protein: 1.4,
      fiber: 1.3,
      vitaminA: 7405,
      vitaminC: 9.2,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD501"],
    description:
      "Fast-growing leafy green, perfect for salad mixes and successive planting",
    growingTips:
      "Plant every 2 weeks for continuous harvest. Prefers cool weather.",
    harvestingTips:
      "Harvest in morning when leaves are crisp. Cut outer leaves first.",
    storageTips: "Store in plastic bag in refrigerator. Use within 5-7 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Spinach",
    scientificName: "Spinacia oleracea",
    commonNames: ["Garden Spinach"],
    category: ProductCategory.VEGETABLES,
    cropType: "LEAFY",
    cropFamily: CropFamily.AMARANTHACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "CLAY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.5, max: 7.5 },
    daysToMaturity: { min: 40, max: 50 },
    plantingDepth: 0.5,
    spacing: { rows: 12, plants: 3 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 10000,
    yieldUnit: "lbs",
    marketPricePerLb: 4.0,
    organicPremium: 1.5,
    inputCostPerAcre: 2800,
    laborHoursPerAcre: 100,
    storageLife: 10,
    priceVolatility: 0.3,
    peakSeason: "Spring, Fall",
    companionPlants: ["Strawberries", "Radishes", "Peas", "Beans"],
    antagonistPlants: ["Potatoes"],
    commonPests: ["Aphids", "Leafminers", "Flea Beetles"],
    commonDiseases: ["Downy Mildew", "White Rust", "Fusarium Wilt"],
    nutritionalInfo: {
      calories: 23,
      protein: 2.9,
      fiber: 2.2,
      iron: 2.7,
      vitaminK: 483,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD501", "BD502"],
    description:
      "Nutrient-dense leafy green, excellent for fresh eating and cooking",
    growingTips:
      "Cold-hardy. Plant early spring or late summer. Bolts in hot weather.",
    harvestingTips:
      "Harvest outer leaves when 4-6 inches. Cut-and-come-again for baby spinach.",
    storageTips:
      "Refrigerate in sealed container with paper towel to absorb moisture.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Kale",
    scientificName: "Brassica oleracea",
    commonNames: ["Borecole", "Leaf Cabbage"],
    category: ProductCategory.VEGETABLES,
    cropType: "LEAFY",
    cropFamily: CropFamily.BRASSICACEAE,
    hardinessZones: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "CLAY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 55, max: 75 },
    plantingDepth: 0.5,
    spacing: { rows: 18, plants: 12 },
    growingSeasons: [Season.SPRING, Season.FALL, Season.WINTER],
    averageYieldPerAcre: 15000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.0,
    organicPremium: 1.45,
    inputCostPerAcre: 3000,
    laborHoursPerAcre: 110,
    storageLife: 14,
    priceVolatility: 0.2,
    peakSeason: "Fall, Winter",
    companionPlants: [
      "Beets",
      "Celery",
      "Cucumbers",
      "Lettuce",
      "Onions",
      "Potatoes",
    ],
    antagonistPlants: ["Strawberries", "Tomatoes", "Beans", "Peppers"],
    commonPests: ["Cabbage Worms", "Aphids", "Flea Beetles"],
    commonDiseases: ["Black Rot", "Clubroot", "Downy Mildew"],
    nutritionalInfo: {
      calories: 35,
      protein: 2.9,
      fiber: 4.1,
      vitaminK: 390,
      vitaminC: 93,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD503"],
    description: "Cold-hardy superfood green, sweeter after frost",
    growingTips: "Frost improves flavor. Excellent winter crop. Heavy feeder.",
    harvestingTips: "Pick outer leaves, leave center to continue growing.",
    storageTips:
      "Store in refrigerator up to 2 weeks. Blanch and freeze for long-term.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Root Crops
  {
    name: "Carrot",
    scientificName: "Daucus carota",
    commonNames: ["Garden Carrot"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.APIACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["SANDY", "LOAMY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 70, max: 80 },
    plantingDepth: 0.25,
    spacing: { rows: 12, plants: 2 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 25000,
    yieldUnit: "lbs",
    marketPricePerLb: 2.0,
    organicPremium: 1.3,
    inputCostPerAcre: 2200,
    laborHoursPerAcre: 140,
    storageLife: 120,
    priceVolatility: 0.15,
    peakSeason: "Fall",
    companionPlants: ["Lettuce", "Radishes", "Onions", "Peas", "Tomatoes"],
    antagonistPlants: ["Dill", "Parsnips"],
    commonPests: ["Carrot Rust Fly", "Wireworms", "Aphids"],
    commonDiseases: [
      "Alternaria Leaf Blight",
      "Cercospora Leaf Spot",
      "Aster Yellows",
    ],
    nutritionalInfo: {
      calories: 41,
      protein: 0.9,
      fiber: 2.8,
      vitaminA: 16706,
      betaCarotene: 8285,
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER", "WANING_CRESCENT"],
    biodynamicPreparations: ["BD500", "BD504"],
    description: "Sweet root vegetable, excellent storage crop",
    growingTips:
      "Needs loose, rock-free soil. Thin seedlings early. No fresh manure.",
    harvestingTips:
      "Harvest when 3/4 inch diameter. Loosen soil before pulling.",
    storageTips: "Store in sand in cool cellar for 4+ months. Remove tops.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Beet",
    scientificName: "Beta vulgaris",
    commonNames: ["Garden Beet", "Table Beet"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.AMARANTHACEAE,
    hardinessZones: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 50, max: 70 },
    plantingDepth: 0.5,
    spacing: { rows: 12, plants: 3 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 20000,
    yieldUnit: "lbs",
    marketPricePerLb: 2.5,
    organicPremium: 1.35,
    inputCostPerAcre: 2400,
    laborHoursPerAcre: 100,
    storageLife: 90,
    priceVolatility: 0.18,
    peakSeason: "Summer, Fall",
    companionPlants: ["Lettuce", "Onions", "Cabbage", "Kale", "Broccoli"],
    antagonistPlants: ["Pole Beans", "Field Mustard"],
    commonPests: ["Flea Beetles", "Aphids", "Leafminers"],
    commonDiseases: ["Cercospora Leaf Spot", "Downy Mildew", "Powdery Mildew"],
    nutritionalInfo: {
      calories: 43,
      protein: 1.6,
      fiber: 2.8,
      folate: 109,
      iron: 0.8,
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Dual-purpose crop - roots and greens both edible",
    growingTips:
      "Thin early for baby beets. Tolerates light frost. Plant succession.",
    harvestingTips:
      "Harvest when 1.5-3 inches. Twist off greens, leave 1 inch stem.",
    storageTips:
      "Store roots in damp sand. Greens refrigerate separately 3-5 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Radish",
    scientificName: "Raphanus sativus",
    commonNames: ["Garden Radish"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.BRASSICACEAE,
    hardinessZones: [2, 3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 22, max: 30 },
    plantingDepth: 0.5,
    spacing: { rows: 6, plants: 1 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 8000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.0,
    organicPremium: 1.3,
    inputCostPerAcre: 1500,
    laborHoursPerAcre: 60,
    storageLife: 14,
    priceVolatility: 0.22,
    peakSeason: "Spring",
    companionPlants: ["Lettuce", "Peas", "Nasturtiums", "Cucumbers", "Carrots"],
    antagonistPlants: ["Hyssop"],
    commonPests: ["Flea Beetles", "Cabbage Root Maggots", "Aphids"],
    commonDiseases: ["Downy Mildew", "White Rust", "Black Root"],
    nutritionalInfo: { calories: 16, protein: 0.7, fiber: 1.6, vitaminC: 14.8 },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500"],
    description: "Fast-growing crop, excellent for succession planting",
    growingTips: "Plant every 10 days. Cool weather preferred. Quick harvest.",
    harvestingTips:
      "Pull when size of marble to golf ball. Overmature becomes pithy.",
    storageTips:
      "Remove greens. Store in plastic bag in refrigerator 1-2 weeks.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Potato",
    scientificName: "Solanum tuberosum",
    commonNames: ["Irish Potato", "White Potato"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.SOLANACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 5.0, max: 6.5 },
    daysToMaturity: { min: 90, max: 120 },
    plantingDepth: 4.0,
    spacing: { rows: 36, plants: 12 },
    growingSeasons: [Season.SPRING],
    averageYieldPerAcre: 30000,
    yieldUnit: "lbs",
    marketPricePerLb: 1.5,
    organicPremium: 1.4,
    inputCostPerAcre: 3500,
    laborHoursPerAcre: 160,
    storageLife: 180,
    priceVolatility: 0.12,
    peakSeason: "Fall",
    companionPlants: ["Beans", "Corn", "Cabbage", "Peas", "Marigolds"],
    antagonistPlants: [
      "Tomatoes",
      "Cucumbers",
      "Squash",
      "Raspberries",
      "Sunflowers",
    ],
    commonPests: ["Colorado Potato Beetle", "Aphids", "Wireworms"],
    commonDiseases: ["Late Blight", "Early Blight", "Scab"],
    nutritionalInfo: {
      calories: 77,
      protein: 2.0,
      fiber: 2.1,
      potassium: 421,
      vitaminC: 19.7,
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD508"],
    description: "Staple crop with excellent storage and high yields",
    growingTips:
      "Hill soil around plants as they grow. Use certified seed potatoes.",
    harvestingTips: "Harvest after vines die back. Cure in dark for 2 weeks.",
    storageTips: "Store in cool (40°F), dark, humid place. Can last 6+ months.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Fruiting Crops
  {
    name: "Tomato",
    scientificName: "Solanum lycopersicum",
    commonNames: ["Garden Tomato"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.SOLANACEAE,
    hardinessZones: [5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 60, max: 85 },
    plantingDepth: 0.25,
    spacing: { rows: 36, plants: 24 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 35000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.5,
    organicPremium: 1.5,
    inputCostPerAcre: 4500,
    laborHoursPerAcre: 200,
    storageLife: 14,
    priceVolatility: 0.35,
    peakSeason: "Summer",
    companionPlants: [
      "Basil",
      "Carrots",
      "Celery",
      "Onions",
      "Parsley",
      "Marigolds",
    ],
    antagonistPlants: ["Brassicas", "Corn", "Fennel", "Potatoes", "Walnuts"],
    commonPests: ["Hornworms", "Aphids", "Whiteflies", "Cutworms"],
    commonDiseases: [
      "Early Blight",
      "Late Blight",
      "Fusarium Wilt",
      "Verticillium Wilt",
    ],
    nutritionalInfo: {
      calories: 18,
      protein: 0.9,
      fiber: 1.2,
      vitaminC: 13.7,
      lycopene: 2573,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS", "FULL_MOON"],
    biodynamicPreparations: ["BD500", "BD501", "BD502", "BD505"],
    description: "Popular summer crop with diverse varieties and uses",
    growingTips:
      "Stake or cage plants. Prune suckers. Consistent watering prevents cracking.",
    harvestingTips:
      "Pick when fully colored. Harvest regularly to encourage production.",
    storageTips:
      "Store at room temperature. Never refrigerate - ruins flavor and texture.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Bell Pepper",
    scientificName: "Capsicum annuum",
    commonNames: ["Sweet Pepper", "Capsicum"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.SOLANACEAE,
    hardinessZones: [5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 70, max: 90 },
    plantingDepth: 0.25,
    spacing: { rows: 24, plants: 18 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 28000,
    yieldUnit: "lbs",
    marketPricePerLb: 4.0,
    organicPremium: 1.6,
    inputCostPerAcre: 4000,
    laborHoursPerAcre: 180,
    storageLife: 10,
    priceVolatility: 0.3,
    peakSeason: "Summer, Early Fall",
    companionPlants: ["Basil", "Onions", "Spinach", "Tomatoes"],
    antagonistPlants: ["Beans", "Brassicas", "Fennel"],
    commonPests: ["Aphids", "Pepper Weevils", "European Corn Borers"],
    commonDiseases: [
      "Bacterial Spot",
      "Phytophthora Blight",
      "Tobacco Mosaic Virus",
    ],
    nutritionalInfo: {
      calories: 31,
      protein: 1.0,
      fiber: 2.1,
      vitaminC: 127.7,
      vitaminA: 3131,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD501", "BD502"],
    description: "Colorful sweet peppers, high market value",
    growingTips:
      "Needs warm soil. Mulch to retain moisture. Stake tall varieties.",
    harvestingTips:
      "Cut with shears. Green peppers mature to red/yellow for sweeter flavor.",
    storageTips: "Refrigerate in crisper drawer. Use within 1-2 weeks.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Cucumber",
    scientificName: "Cucumis sativus",
    commonNames: ["Garden Cucumber"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.CUCURBITACEAE,
    hardinessZones: [4, 5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "HIGH",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 50, max: 70 },
    plantingDepth: 1.0,
    spacing: { rows: 60, plants: 12 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 20000,
    yieldUnit: "lbs",
    marketPricePerLb: 2.0,
    organicPremium: 1.4,
    inputCostPerAcre: 3000,
    laborHoursPerAcre: 140,
    storageLife: 7,
    priceVolatility: 0.28,
    peakSeason: "Summer",
    companionPlants: ["Beans", "Corn", "Peas", "Radishes", "Sunflowers"],
    antagonistPlants: ["Aromatic Herbs", "Potatoes", "Melons"],
    commonPests: ["Cucumber Beetles", "Aphids", "Squash Bugs"],
    commonDiseases: ["Powdery Mildew", "Downy Mildew", "Bacterial Wilt"],
    nutritionalInfo: { calories: 15, protein: 0.7, fiber: 0.5, vitaminK: 16.4 },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD501"],
    description:
      "Fast-growing summer crop, excellent for fresh eating and pickles",
    growingTips:
      "Needs consistent moisture. Trellis for better production and disease prevention.",
    harvestingTips:
      "Pick daily when fruits reach 6-8 inches. Overripe cukes are bitter.",
    storageTips: "Refrigerate unwashed. Use within 3-5 days for best quality.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Zucchini",
    scientificName: "Cucurbita pepo",
    commonNames: ["Summer Squash", "Courgette"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.CUCURBITACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 45, max: 55 },
    plantingDepth: 1.0,
    spacing: { rows: 48, plants: 36 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 25000,
    yieldUnit: "lbs",
    marketPricePerLb: 2.5,
    organicPremium: 1.35,
    inputCostPerAcre: 2800,
    laborHoursPerAcre: 120,
    storageLife: 7,
    priceVolatility: 0.25,
    peakSeason: "Summer",
    companionPlants: ["Beans", "Corn", "Peas", "Radishes"],
    antagonistPlants: ["Potatoes"],
    commonPests: ["Squash Bugs", "Cucumber Beetles", "Squash Vine Borers"],
    commonDiseases: ["Powdery Mildew", "Bacterial Wilt", "Mosaic Virus"],
    nutritionalInfo: { calories: 17, protein: 1.2, fiber: 1.0, vitaminC: 17.9 },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Prolific producer, versatile summer squash",
    growingTips:
      "Plant after frost danger. Harvest regularly to encourage production.",
    harvestingTips: "Pick when 6-8 inches for best flavor. Check plants daily.",
    storageTips: "Refrigerate unwashed. Use within 4-5 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Eggplant",
    scientificName: "Solanum melongena",
    commonNames: ["Aubergine", "Brinjal"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.SOLANACEAE,
    hardinessZones: [5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 5.5, max: 6.5 },
    daysToMaturity: { min: 70, max: 85 },
    plantingDepth: 0.25,
    spacing: { rows: 30, plants: 24 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 20000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.5,
    organicPremium: 1.45,
    inputCostPerAcre: 3800,
    laborHoursPerAcre: 170,
    storageLife: 7,
    priceVolatility: 0.32,
    peakSeason: "Summer, Early Fall",
    companionPlants: ["Beans", "Peppers", "Spinach", "Thyme"],
    antagonistPlants: ["Tomatoes", "Potatoes"],
    commonPests: ["Flea Beetles", "Colorado Potato Beetles", "Aphids"],
    commonDiseases: ["Verticillium Wilt", "Phomopsis Blight", "Bacterial Wilt"],
    nutritionalInfo: {
      calories: 25,
      protein: 1.0,
      fiber: 3.0,
      manganese: 0.23,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD501"],
    description: "Heat-loving crop, excellent for Mediterranean dishes",
    growingTips:
      "Needs hot weather. Black plastic mulch warms soil. Stake plants.",
    harvestingTips: "Pick when skin is glossy. Dull skin means overripe.",
    storageTips:
      "Store at room temperature. Use within 2-3 days for best quality.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Brassicas
  {
    name: "Broccoli",
    scientificName: "Brassica oleracea var. italica",
    commonNames: ["Calabrese"],
    category: ProductCategory.VEGETABLES,
    cropType: "FLOWER",
    cropFamily: CropFamily.BRASSICACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "CLAY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 55, max: 85 },
    plantingDepth: 0.5,
    spacing: { rows: 24, plants: 18 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 18000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.0,
    organicPremium: 1.5,
    inputCostPerAcre: 3500,
    laborHoursPerAcre: 150,
    storageLife: 7,
    priceVolatility: 0.25,
    peakSeason: "Spring, Fall",
    companionPlants: [
      "Beets",
      "Celery",
      "Cucumbers",
      "Lettuce",
      "Onions",
      "Potatoes",
    ],
    antagonistPlants: ["Strawberries", "Tomatoes"],
    commonPests: ["Cabbage Worms", "Aphids", "Flea Beetles"],
    commonDiseases: ["Black Rot", "Clubroot", "Downy Mildew"],
    nutritionalInfo: {
      calories: 34,
      protein: 2.8,
      fiber: 2.6,
      vitaminC: 89.2,
      vitaminK: 101.6,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD503"],
    description: "Nutrient-dense cruciferous vegetable, produces side shoots",
    growingTips: "Cool weather crop. Heavy feeder. Plant spring and fall.",
    harvestingTips: "Cut main head when tight. Side shoots continue producing.",
    storageTips: "Refrigerate in plastic bag. Use within 5-7 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Cauliflower",
    scientificName: "Brassica oleracea var. botrytis",
    commonNames: ["Curd", "Heading Broccoli"],
    category: ProductCategory.VEGETABLES,
    cropType: "FLOWER",
    cropFamily: CropFamily.BRASSICACEAE,
    hardinessZones: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "CLAY"],
    waterRequirements: "HIGH",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 55, max: 100 },
    plantingDepth: 0.5,
    spacing: { rows: 24, plants: 18 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 16000,
    yieldUnit: "lbs",
    marketPricePerLb: 3.5,
    organicPremium: 1.55,
    inputCostPerAcre: 4000,
    laborHoursPerAcre: 160,
    storageLife: 7,
    priceVolatility: 0.28,
    peakSeason: "Fall",
    companionPlants: ["Beets", "Celery", "Onions", "Potatoes"],
    antagonistPlants: ["Strawberries", "Tomatoes"],
    commonPests: ["Cabbage Worms", "Aphids", "Flea Beetles"],
    commonDiseases: ["Black Rot", "Clubroot", "Downy Mildew"],
    nutritionalInfo: { calories: 25, protein: 1.9, fiber: 2.0, vitaminC: 48.2 },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD503"],
    description: "Premium brassica, requires careful attention",
    growingTips:
      "Needs consistent moisture. Blanch heads by tying leaves. Cool weather.",
    harvestingTips: "Cut when head is 6-8 inches, tight and white.",
    storageTips: "Refrigerate stem-side down. Use within 5-7 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Cabbage",
    scientificName: "Brassica oleracea var. capitata",
    commonNames: ["Head Cabbage"],
    category: ProductCategory.VEGETABLES,
    cropType: "LEAFY",
    cropFamily: CropFamily.BRASSICACEAE,
    hardinessZones: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "CLAY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 70, max: 120 },
    plantingDepth: 0.5,
    spacing: { rows: 24, plants: 18 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 30000,
    yieldUnit: "lbs",
    marketPricePerLb: 1.5,
    organicPremium: 1.4,
    inputCostPerAcre: 3200,
    laborHoursPerAcre: 140,
    storageLife: 120,
    priceVolatility: 0.15,
    peakSeason: "Fall",
    companionPlants: [
      "Beets",
      "Celery",
      "Cucumbers",
      "Lettuce",
      "Onions",
      "Potatoes",
    ],
    antagonistPlants: ["Strawberries", "Tomatoes", "Grapes"],
    commonPests: ["Cabbage Worms", "Aphids", "Cabbage Loopers"],
    commonDiseases: ["Black Rot", "Clubroot", "Yellows"],
    nutritionalInfo: {
      calories: 25,
      protein: 1.3,
      fiber: 2.5,
      vitaminC: 36.6,
      vitaminK: 76,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD503"],
    description: "Reliable storage crop, versatile uses",
    growingTips:
      "Heavy feeder. Consistent watering prevents splitting. Cool weather.",
    harvestingTips: "Cut when firm. Can withstand light frost.",
    storageTips:
      "Store in cool cellar. Can last 3-4 months wrapped in newspaper.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Legumes
  {
    name: "Green Beans",
    scientificName: "Phaseolus vulgaris",
    commonNames: ["Snap Beans", "String Beans"],
    category: ProductCategory.VEGETABLES,
    cropType: "SEED",
    cropFamily: CropFamily.FABACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 50, max: 60 },
    plantingDepth: 1.0,
    spacing: { rows: 24, plants: 4 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 8000,
    yieldUnit: "lbs",
    marketPricePerLb: 4.0,
    organicPremium: 1.4,
    inputCostPerAcre: 2000,
    laborHoursPerAcre: 180,
    storageLife: 7,
    priceVolatility: 0.3,
    peakSeason: "Summer",
    companionPlants: ["Carrots", "Corn", "Cucumbers", "Potatoes", "Radishes"],
    antagonistPlants: ["Onions", "Garlic", "Fennel", "Peppers"],
    commonPests: ["Mexican Bean Beetles", "Aphids", "Spider Mites"],
    commonDiseases: ["Bean Mosaic Virus", "Bacterial Blight", "Anthracnose"],
    nutritionalInfo: {
      calories: 31,
      protein: 1.8,
      fiber: 2.7,
      vitaminC: 12.2,
      folate: 33,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD507"],
    description: "Easy-to-grow legume, fixes nitrogen in soil",
    growingTips:
      "Direct seed after frost. Bush beans easier than pole. Succession plant.",
    harvestingTips:
      "Pick when pencil-thick. Regular harvesting extends production.",
    storageTips: "Refrigerate unwashed in bag. Use within 3-5 days.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Peas",
    scientificName: "Pisum sativum",
    commonNames: ["Garden Peas", "English Peas"],
    category: ProductCategory.VEGETABLES,
    cropType: "SEED",
    cropFamily: CropFamily.FABACEAE,
    hardinessZones: [2, 3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 55, max: 70 },
    plantingDepth: 1.5,
    spacing: { rows: 24, plants: 2 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 5000,
    yieldUnit: "lbs",
    marketPricePerLb: 5.0,
    organicPremium: 1.5,
    inputCostPerAcre: 2200,
    laborHoursPerAcre: 200,
    storageLife: 5,
    priceVolatility: 0.35,
    peakSeason: "Spring",
    companionPlants: [
      "Beans",
      "Carrots",
      "Corn",
      "Cucumbers",
      "Radishes",
      "Turnips",
    ],
    antagonistPlants: ["Onions", "Garlic", "Potatoes"],
    commonPests: ["Aphids", "Pea Weevils", "Thrips"],
    commonDiseases: ["Powdery Mildew", "Fusarium Wilt", "Root Rot"],
    nutritionalInfo: {
      calories: 81,
      protein: 5.4,
      fiber: 5.7,
      vitaminC: 40,
      vitaminK: 24.8,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD507"],
    description: "Cool-season legume, sweet and nutritious",
    growingTips:
      "Plant early spring. Provide support for climbing. Frost tolerant.",
    harvestingTips:
      "Pick when pods are full but still tender. Daily harvesting encouraged.",
    storageTips:
      "Best eaten fresh. Refrigerate in pod 3-5 days. Freeze for long storage.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Alliums
  {
    name: "Onion",
    scientificName: "Allium cepa",
    commonNames: ["Bulb Onion", "Garden Onion"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.AMARYLLIDACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 100, max: 120 },
    plantingDepth: 0.5,
    spacing: { rows: 12, plants: 4 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 30000,
    yieldUnit: "lbs",
    marketPricePerLb: 1.5,
    organicPremium: 1.35,
    inputCostPerAcre: 3000,
    laborHoursPerAcre: 150,
    storageLife: 180,
    priceVolatility: 0.2,
    peakSeason: "Summer, Fall",
    companionPlants: ["Beets", "Carrots", "Lettuce", "Tomatoes", "Peppers"],
    antagonistPlants: ["Beans", "Peas", "Asparagus", "Sage"],
    commonPests: ["Onion Maggots", "Thrips", "Onion Root Maggots"],
    commonDiseases: ["Downy Mildew", "Botrytis Leaf Blight", "Pink Root"],
    nutritionalInfo: {
      calories: 40,
      protein: 1.1,
      fiber: 1.7,
      vitaminC: 7.4,
      quercetin: "high",
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Versatile storage crop, staple vegetable",
    growingTips:
      "Plant sets or transplants. Stop watering when tops fall over.",
    harvestingTips:
      "Harvest when tops fall. Cure in warm, dry place for 2-3 weeks.",
    storageTips:
      "Store in cool, dry, dark place with good air circulation. Can last 6+ months.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Garlic",
    scientificName: "Allium sativum",
    commonNames: ["Common Garlic", "Stinking Rose"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.AMARYLLIDACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 240, max: 270 },
    plantingDepth: 2.0,
    spacing: { rows: 12, plants: 6 },
    growingSeasons: [Season.FALL, Season.WINTER, Season.SPRING],
    averageYieldPerAcre: 8000,
    yieldUnit: "lbs",
    marketPricePerLb: 8.0,
    organicPremium: 1.6,
    inputCostPerAcre: 3500,
    laborHoursPerAcre: 200,
    storageLife: 240,
    priceVolatility: 0.25,
    peakSeason: "Summer",
    companionPlants: ["Tomatoes", "Roses", "Carrots", "Beets"],
    antagonistPlants: ["Beans", "Peas", "Asparagus", "Strawberries"],
    commonPests: ["Onion Maggots", "Thrips", "Nematodes"],
    commonDiseases: ["White Rot", "Fusarium Rot", "Purple Blotch"],
    nutritionalInfo: {
      calories: 149,
      protein: 6.4,
      fiber: 2.1,
      vitaminC: 31.2,
      manganese: 1.67,
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502", "BD508"],
    description: "High-value crop with long storage, medicinal properties",
    growingTips:
      "Plant in fall. Needs cold period for bulb formation. Remove scapes.",
    harvestingTips: "Harvest when half of tops turn brown. Cure for 3-4 weeks.",
    storageTips: "Braid or hang in cool, dry place. Can last 8+ months.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Leek",
    scientificName: "Allium ampeloprasum",
    commonNames: ["Garden Leek"],
    category: ProductCategory.VEGETABLES,
    cropType: "ROOT",
    cropFamily: CropFamily.AMARYLLIDACEAE,
    hardinessZones: [5, 6, 7, 8, 9],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.0 },
    daysToMaturity: { min: 120, max: 150 },
    plantingDepth: 0.25,
    spacing: { rows: 12, plants: 6 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 12000,
    yieldUnit: "lbs",
    marketPricePerLb: 4.0,
    organicPremium: 1.5,
    inputCostPerAcre: 3200,
    laborHoursPerAcre: 180,
    storageLife: 90,
    priceVolatility: 0.22,
    peakSeason: "Fall, Winter",
    companionPlants: ["Carrots", "Celery", "Onions"],
    antagonistPlants: ["Beans", "Peas"],
    commonPests: ["Onion Maggots", "Thrips", "Leafminers"],
    commonDiseases: ["Downy Mildew", "White Tip", "Purple Blotch"],
    nutritionalInfo: {
      calories: 61,
      protein: 1.5,
      fiber: 1.8,
      vitaminK: 47,
      folate: 64,
    },
    lunarPlantingPhases: ["WANING_GIBBOUS", "LAST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Premium allium with mild flavor, excellent for soups",
    growingTips:
      "Hill soil around stems for blanching. Needs long growing season.",
    harvestingTips:
      "Harvest when stems are 1-2 inches diameter. Can withstand frost.",
    storageTips:
      "Store in cool place with roots attached. Use within 2-3 months.",
    isActive: true,
    isFeatured: true,
  },

  // VEGETABLES - Winter Squash & Pumpkins
  {
    name: "Butternut Squash",
    scientificName: "Cucurbita moschata",
    commonNames: ["Winter Squash"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.CUCURBITACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 85, max: 110 },
    plantingDepth: 1.0,
    spacing: { rows: 72, plants: 48 },
    growingSeasons: [Season.SUMMER, Season.FALL],
    averageYieldPerAcre: 20000,
    yieldUnit: "lbs",
    marketPricePerLb: 2.0,
    organicPremium: 1.4,
    inputCostPerAcre: 3000,
    laborHoursPerAcre: 130,
    storageLife: 180,
    priceVolatility: 0.18,
    peakSeason: "Fall",
    companionPlants: ["Beans", "Corn", "Peas", "Radishes"],
    antagonistPlants: ["Potatoes"],
    commonPests: ["Squash Bugs", "Cucumber Beetles", "Squash Vine Borers"],
    commonDiseases: ["Powdery Mildew", "Downy Mildew", "Bacterial Wilt"],
    nutritionalInfo: {
      calories: 45,
      protein: 1.0,
      fiber: 2.0,
      vitaminA: 10630,
      vitaminC: 21,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Popular winter squash with excellent storage",
    growingTips:
      "Needs long season. Leave on vine until frost. Cure before storage.",
    harvestingTips:
      "Harvest when skin is hard, stem is brown. Leave 2-inch stem.",
    storageTips:
      "Cure 2 weeks at 80°F. Store in cool (50-60°F), dry place 3-6 months.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Pumpkin",
    scientificName: "Cucurbita pepo",
    commonNames: ["Field Pumpkin", "Jack-o-Lantern"],
    category: ProductCategory.VEGETABLES,
    cropType: "FRUIT",
    cropFamily: CropFamily.CUCURBITACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 6.8 },
    daysToMaturity: { min: 90, max: 120 },
    plantingDepth: 1.0,
    spacing: { rows: 96, plants: 60 },
    growingSeasons: [Season.SUMMER, Season.FALL],
    averageYieldPerAcre: 25000,
    yieldUnit: "lbs",
    marketPricePerLb: 0.5,
    organicPremium: 1.3,
    inputCostPerAcre: 2500,
    laborHoursPerAcre: 120,
    storageLife: 120,
    priceVolatility: 0.25,
    peakSeason: "Fall",
    companionPlants: ["Beans", "Corn", "Peas"],
    antagonistPlants: ["Potatoes"],
    commonPests: ["Squash Bugs", "Cucumber Beetles", "Squash Vine Borers"],
    commonDiseases: ["Powdery Mildew", "Downy Mildew", "Bacterial Wilt"],
    nutritionalInfo: {
      calories: 26,
      protein: 1.0,
      fiber: 0.5,
      vitaminA: 8513,
      potassium: 340,
    },
    lunarPlantingPhases: ["FIRST_QUARTER", "WAXING_GIBBOUS"],
    biodynamicPreparations: ["BD500", "BD502"],
    description: "Versatile crop for eating and decoration, high yields",
    growingTips:
      "Needs lots of space. Pinch vines for larger fruits. Harvest before frost.",
    harvestingTips: "Harvest when orange, skin is hard. Leave 3-4 inch stem.",
    storageTips: "Cure 2 weeks. Store in cool, dry place 2-4 months.",
    isActive: true,
    isFeatured: true,
  },

  // HERBS
  {
    name: "Basil",
    scientificName: "Ocimum basilicum",
    commonNames: ["Sweet Basil", "Genovese Basil"],
    category: ProductCategory.HERBS,
    cropType: "LEAFY",
    cropFamily: CropFamily.LAMIACEAE,
    hardinessZones: [4, 5, 6, 7, 8, 9, 10, 11],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "FULL_SUN",
    phRange: { min: 6.0, max: 7.5 },
    daysToMaturity: { min: 45, max: 60 },
    plantingDepth: 0.25,
    spacing: { rows: 12, plants: 8 },
    growingSeasons: [Season.SUMMER],
    averageYieldPerAcre: 3000,
    yieldUnit: "lbs",
    marketPricePerLb: 12.0,
    organicPremium: 1.5,
    inputCostPerAcre: 2000,
    laborHoursPerAcre: 150,
    storageLife: 3,
    priceVolatility: 0.3,
    peakSeason: "Summer",
    companionPlants: ["Tomatoes", "Peppers", "Asparagus", "Oregano"],
    antagonistPlants: ["Rue", "Sage"],
    commonPests: ["Aphids", "Japanese Beetles", "Slugs"],
    commonDiseases: ["Downy Mildew", "Fusarium Wilt", "Leaf Spot"],
    nutritionalInfo: {
      calories: 23,
      protein: 3.2,
      fiber: 1.6,
      vitaminK: 414.8,
    },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD501"],
    description: "Popular culinary herb, high value per pound",
    growingTips:
      "Pinch flowers to encourage leaf production. Harvest regularly.",
    harvestingTips:
      "Cut stems, not just leaves. Harvest in morning for best flavor.",
    storageTips:
      "Best fresh. Store stems in water like flowers. Freezes well in oil.",
    isActive: true,
    isFeatured: true,
  },
  {
    name: "Cilantro",
    scientificName: "Coriandrum sativum",
    commonNames: ["Coriander", "Chinese Parsley"],
    category: ProductCategory.HERBS,
    cropType: "LEAFY",
    cropFamily: CropFamily.APIACEAE,
    hardinessZones: [3, 4, 5, 6, 7, 8, 9, 10],
    soilPreferences: ["LOAMY", "SANDY"],
    waterRequirements: "MODERATE",
    sunRequirements: "PARTIAL_SHADE",
    phRange: { min: 6.2, max: 6.8 },
    daysToMaturity: { min: 45, max: 55 },
    plantingDepth: 0.5,
    spacing: { rows: 6, plants: 2 },
    growingSeasons: [Season.SPRING, Season.FALL],
    averageYieldPerAcre: 2500,
    yieldUnit: "lbs",
    marketPricePerLb: 10.0,
    organicPremium: 1.45,
    inputCostPerAcre: 1800,
    laborHoursPerAcre: 120,
    storageLife: 5,
    priceVolatility: 0.28,
    peakSeason: "Spring, Fall",
    companionPlants: ["Dill", "Anise", "Coriander"],
    antagonistPlants: ["Fennel"],
    commonPests: ["Aphids", "Whiteflies"],
    commonDiseases: ["Bacterial Leaf Spot", "Powdery Mildew"],
    nutritionalInfo: { calories: 23, protein: 2.1, fiber: 2.8, vitaminK: 310 },
    lunarPlantingPhases: ["WAXING_CRESCENT", "FIRST_QUARTER"],
    biodynamicPreparations: ["BD500", "BD501"],
    description: "Fast-growing herb with distinctive flavor",
    growingTips: "Bolts quickly in heat. Plant succession every 2 weeks.",
    harvestingTips: "Cut before flowering. Use fresh for best flavor.",
    storageTips: "Store in water in refrigerator. Freezes well.",
    isActive: true,
    isFeatured: true,
  },
];

/**
 * Seed the crops database
 */
async function seedCrops() {
  console.log("🌾 Seeding crops database...");
  console.log(`📊 Processing ${crops.length} crops...`);

  // Delete existing crops to avoid conflicts
  await prisma.crop.deleteMany({});
  console.log("🗑️  Cleared existing crops");

  // Create all crops in a single transaction
  const result = await prisma.crop.createMany({
    data: crops,
    skipDuplicates: true,
  });

  console.log(`✅ Successfully seeded ${result.count} crops`);
}

/**
 * Main seed function
 */
async function main() {
  try {
    await seedCrops();
    console.log("🎉 Crop database seeding completed successfully!");
  } catch (error) {
    console.error("❌ Error seeding crops:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run if called directly (ES module compatible)
console.log("🚀 Starting seed script...");
main().catch((error) => {
  console.error("❌ Fatal error:", error);
  process.exit(1);
});

export { crops, seedCrops };
