name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to see
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe what you actually see, including any error messages
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application is unusable
        - High - Major functionality is broken
        - Medium - Some functionality is affected
        - Low - Minor issue or cosmetic
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Authentication
        - Farmer Dashboard
        - Customer Marketplace
        - Product Management
        - Order Management
        - Payments
        - Notifications
        - Search/Filters
        - Admin Panel
        - API
        - Database
        - Other
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL (if applicable)
      description: The URL where the bug occurs
      placeholder: https://farmersmarket.com/...

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this bug occur?
      options:
        - Production
        - Staging
        - Development (Local)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 120.0.6099.109

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: e.g., Windows 11, macOS 14.2, iOS 17.2, Android 14

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Copy and paste any relevant error messages or console logs
      render: shell
      placeholder: |
        Paste error messages, stack traces, or console output here

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information about the problem
      placeholder: |
        - User role (Farmer, Customer, Admin)
        - Data involved (order ID, farm ID, etc.)
        - Recent changes or actions
        - Frequency of occurrence

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I can reproduce this bug consistently
          required: false
        - label: This bug affects multiple users (not just me)
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## What happens next?

        1. **Triage** - We'll review your issue within 48 hours
        2. **Investigation** - We'll attempt to reproduce the bug
        3. **Fix** - We'll prioritize and fix based on severity
        4. **Update** - We'll keep you updated on progress

        Thank you for helping us improve the Farmers Market Platform! 🌾
