#!/usr/bin/env pwsh
# ============================================
# DIVINE DOCKER MANAGER
# Quantum Database & Service Orchestration
# ============================================

param(
  [Parameter(Mandatory = $false)]
  [ValidateSet("up", "down", "restart", "status", "logs", "clean", "init")]
  [string]$Action = "status",

  [Parameter(Mandatory = $false)]
  [switch]$Detached = $true,

  [Parameter(Mandatory = $false)]
  [switch]$Build = $false,

  [Parameter(Mandatory = $false)]
  [string]$Service = ""
)

Write-Host "🐳 DIVINE DOCKER MANAGER" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host ""

# Check if Docker is installed
function Test-DockerInstalled {
  try {
    $null = docker --version 2>&1
    return $true
  }
  catch {
    return $false
  }
}

# Check if Docker daemon is running
function Test-DockerRunning {
  try {
    $null = docker ps 2>&1
    return $LASTEXITCODE -eq 0
  }
  catch {
    return $false
  }
}

# Check if docker-compose.yml exists
function Test-DockerComposeExists {
  $composePath = Join-Path $PSScriptRoot ".." "docker-compose.yml"
  return Test-Path $composePath
}

# Create docker-compose.yml if it doesn't exist
function Initialize-DockerCompose {
  $composePath = Join-Path $PSScriptRoot ".." "docker-compose.yml"

  if (Test-Path $composePath) {
    Write-Host "✅ docker-compose.yml already exists" -ForegroundColor Green
    return
  }

  Write-Host "📝 Creating divine docker-compose.yml..." -ForegroundColor Yellow

  $composeContent = @"
version: '3.9'

services:
  # PostgreSQL Divine Database
  postgres:
    image: postgres:16-alpine
    container_name: farmers-market-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: divine_user
      POSTGRES_PASSWORD: quantum_password
      POSTGRES_DB: farmers_market
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - divine-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U divine_user -d farmers_market"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Divine Cache
  redis:
    image: redis:7-alpine
    container_name: farmers-market-cache
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass quantum_cache_password
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - divine-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  divine-network:
    driver: bridge
"@

  Set-Content -Path $composePath -Value $composeContent -Encoding UTF8
  Write-Host "✅ docker-compose.yml created successfully" -ForegroundColor Green
}

# Create .env.docker if it doesn't exist
function Initialize-DockerEnv {
  $envPath = Join-Path $PSScriptRoot ".." ".env.docker"

  if (Test-Path $envPath) {
    Write-Host "✅ .env.docker already exists" -ForegroundColor Green
    return
  }

  Write-Host "📝 Creating .env.docker..." -ForegroundColor Yellow

  $envContent = @"
# Docker Environment Variables
# Generated by Divine Docker Manager

# PostgreSQL Configuration
POSTGRES_USER=divine_user
POSTGRES_PASSWORD=quantum_password
POSTGRES_DB=farmers_market
DATABASE_URL=postgresql://divine_user:quantum_password@localhost:5432/farmers_market

# Redis Configuration
REDIS_PASSWORD=quantum_cache_password
REDIS_URL=redis://:quantum_cache_password@localhost:6379

# Node Environment
NODE_ENV=development
"@

  Set-Content -Path $envPath -Value $envContent -Encoding UTF8
  Write-Host "✅ .env.docker created successfully" -ForegroundColor Green
}

# Main execution
Write-Host "🔍 Checking Docker status..." -ForegroundColor Yellow

if (-not (Test-DockerInstalled)) {
  Write-Host "❌ Docker is not installed" -ForegroundColor Red
  Write-Host "   Please install Docker Desktop from: https://www.docker.com/products/docker-desktop" -ForegroundColor Yellow
  exit 1
}

Write-Host "✅ Docker is installed" -ForegroundColor Green

if (-not (Test-DockerRunning)) {
  Write-Host "⚠️  Docker daemon is not running" -ForegroundColor Yellow
  Write-Host "   Starting Docker Desktop..." -ForegroundColor Yellow

  # Try to start Docker Desktop
  $dockerDesktop = "C:\Program Files\Docker\Docker\Docker Desktop.exe"
  if (Test-Path $dockerDesktop) {
    Start-Process $dockerDesktop
    Write-Host "   Waiting for Docker to start..." -ForegroundColor Yellow

    # Wait up to 60 seconds for Docker to start
    $timeout = 60
    $elapsed = 0
    while ($elapsed -lt $timeout) {
      Start-Sleep -Seconds 2
      $elapsed += 2
      if (Test-DockerRunning) {
        Write-Host "✅ Docker started successfully" -ForegroundColor Green
        break
      }
    }

    if (-not (Test-DockerRunning)) {
      Write-Host "❌ Docker failed to start within $timeout seconds" -ForegroundColor Red
      Write-Host "   Please start Docker Desktop manually" -ForegroundColor Yellow
      exit 1
    }
  }
  else {
    Write-Host "❌ Docker Desktop not found at expected path" -ForegroundColor Red
    Write-Host "   Please start Docker Desktop manually" -ForegroundColor Yellow
    exit 1
  }
}

Write-Host "✅ Docker daemon is running" -ForegroundColor Green
Write-Host ""

# Execute requested action
switch ($Action) {
  "init" {
    Write-Host "🚀 Initializing Docker environment..." -ForegroundColor Cyan
    Initialize-DockerCompose
    Initialize-DockerEnv

    Write-Host ""
    Write-Host "✅ Docker environment initialized" -ForegroundColor Green
    Write-Host "   Next step: Run 'pwsh scripts/divine-docker-manager.ps1 -Action up'" -ForegroundColor Yellow
  }

  "up" {
    if (-not (Test-DockerComposeExists)) {
      Write-Host "⚠️  docker-compose.yml not found" -ForegroundColor Yellow
      Write-Host "   Initializing Docker environment first..." -ForegroundColor Yellow
      Initialize-DockerCompose
      Initialize-DockerEnv
      Write-Host ""
    }

    Write-Host "🚀 Starting Docker services..." -ForegroundColor Cyan

    $args = @("up")
    if ($Detached) { $args += "-d" }
    if ($Build) { $args += "--build" }
    if ($Service) { $args += $Service }

    docker-compose $args

    if ($LASTEXITCODE -eq 0) {
      Write-Host ""
      Write-Host "✅ Docker services started successfully" -ForegroundColor Green
      Write-Host ""
      Write-Host "📊 Service Status:" -ForegroundColor Cyan
      docker-compose ps

      Write-Host ""
      Write-Host "🔗 Connection Information:" -ForegroundColor Cyan
      Write-Host "   PostgreSQL: postgresql://divine_user:quantum_password@localhost:5432/farmers_market" -ForegroundColor White
      Write-Host "   Redis:      redis://:quantum_cache_password@localhost:6379" -ForegroundColor White
    }
    else {
      Write-Host "❌ Failed to start Docker services" -ForegroundColor Red
      exit 1
    }
  }

  "down" {
    Write-Host "🛑 Stopping Docker services..." -ForegroundColor Yellow
    docker-compose down

    if ($LASTEXITCODE -eq 0) {
      Write-Host "✅ Docker services stopped" -ForegroundColor Green
    }
  }

  "restart" {
    Write-Host "🔄 Restarting Docker services..." -ForegroundColor Yellow

    if ($Service) {
      docker-compose restart $Service
    }
    else {
      docker-compose restart
    }

    if ($LASTEXITCODE -eq 0) {
      Write-Host "✅ Docker services restarted" -ForegroundColor Green
    }
  }

  "status" {
    if (-not (Test-DockerComposeExists)) {
      Write-Host "⚠️  docker-compose.yml not found" -ForegroundColor Yellow
      Write-Host "   Run 'pwsh scripts/divine-docker-manager.ps1 -Action init' to initialize" -ForegroundColor Yellow
      exit 0
    }

    Write-Host "📊 Docker Services Status:" -ForegroundColor Cyan
    Write-Host ""
    docker-compose ps

    Write-Host ""
    Write-Host "🔍 Health Checks:" -ForegroundColor Cyan

    # Check PostgreSQL
    $pgRunning = docker ps --filter "name=farmers-market-db" --filter "status=running" -q
    if ($pgRunning) {
      Write-Host "   ✅ PostgreSQL is running" -ForegroundColor Green

      # Test connection
      $pgHealth = docker exec farmers-market-db pg_isready -U divine_user -d farmers_market 2>&1
      if ($LASTEXITCODE -eq 0) {
        Write-Host "      ✅ PostgreSQL is healthy and accepting connections" -ForegroundColor Green
      }
      else {
        Write-Host "      ⚠️  PostgreSQL is running but not healthy" -ForegroundColor Yellow
      }
    }
    else {
      Write-Host "   ❌ PostgreSQL is not running" -ForegroundColor Red
      Write-Host "      Run: pwsh scripts/divine-docker-manager.ps1 -Action up" -ForegroundColor Yellow
    }

    # Check Redis
    $redisRunning = docker ps --filter "name=farmers-market-cache" --filter "status=running" -q
    if ($redisRunning) {
      Write-Host "   ✅ Redis is running" -ForegroundColor Green
    }
    else {
      Write-Host "   ⚠️  Redis is not running" -ForegroundColor Yellow
      Write-Host "      Run: pwsh scripts/divine-docker-manager.ps1 -Action up" -ForegroundColor Yellow
    }
  }

  "logs" {
    Write-Host "📜 Docker Service Logs:" -ForegroundColor Cyan
    Write-Host ""

    if ($Service) {
      docker-compose logs -f --tail=100 $Service
    }
    else {
      docker-compose logs -f --tail=100
    }
  }

  "clean" {
    Write-Host "🧹 Cleaning Docker resources..." -ForegroundColor Yellow

    # Stop services
    docker-compose down

    # Remove volumes (with confirmation)
    $confirm = Read-Host "⚠️  Remove all volumes? This will delete all database data! (y/N)"
    if ($confirm -eq "y" -or $confirm -eq "Y") {
      docker-compose down -v
      Write-Host "✅ Volumes removed" -ForegroundColor Green
    }

    # Remove unused images
    docker image prune -f

    Write-Host "✅ Docker resources cleaned" -ForegroundColor Green
  }
}

Write-Host ""
Write-Host "🌟 Divine Docker Manager - Operation Complete" -ForegroundColor Cyan
