@echo off
REM ⚡ TEST DATABASE SETUP SCRIPT (Windows)
REM Divine Agricultural Platform - Quick Test Database Setup
REM
REM Usage:
REM   scripts\setup-test-db.bat
REM   or
REM   npm run db:test:setup

setlocal enabledelayedexpansion

REM Default configuration
set DEFAULT_HOST=localhost
set DEFAULT_PORT=5432
set DEFAULT_DB=farmersmarket_test
set DEFAULT_USER=postgres
set DEFAULT_PASSWORD=postgres

REM Get configuration from environment or use defaults
if "%TEST_DB_HOST%"=="" (set DB_HOST=%DEFAULT_HOST%) else (set DB_HOST=%TEST_DB_HOST%)
if "%TEST_DB_PORT%"=="" (set DB_PORT=%DEFAULT_PORT%) else (set DB_PORT=%TEST_DB_PORT%)
if "%TEST_DB_NAME%"=="" (set DB_NAME=%DEFAULT_DB%) else (set DB_NAME=%TEST_DB_NAME%)
if "%TEST_DB_USER%"=="" (set DB_USER=%DEFAULT_USER%) else (set DB_USER=%TEST_DB_USER%)
if "%TEST_DB_PASSWORD%"=="" (set DB_PASSWORD=%DEFAULT_PASSWORD%) else (set DB_PASSWORD=%TEST_DB_PASSWORD%)

set DATABASE_URL=postgresql://%DB_USER%:%DB_PASSWORD%@%DB_HOST%:%DB_PORT%/%DB_NAME%

echo.
echo ============================================================
echo   🌾 Divine Agricultural Platform - Test Database Setup
echo ============================================================
echo.

REM Step 1: Check PostgreSQL installation
echo Step 1: Checking PostgreSQL installation...
where psql >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ PostgreSQL is not installed or not in PATH
    echo.
    echo Please install PostgreSQL:
    echo   Download from https://www.postgresql.org/download/windows/
    echo   Or install via Chocolatey: choco install postgresql
    echo.
    pause
    exit /b 1
)
echo ✅ PostgreSQL is installed
echo.

REM Step 2: Display configuration
echo Step 2: Test Database Configuration
echo    Host:     %DB_HOST%
echo    Port:     %DB_PORT%
echo    Database: %DB_NAME%
echo    User:     %DB_USER%
echo.

REM Step 3: Check if PostgreSQL is running
echo Step 3: Checking if PostgreSQL is running...
set PGPASSWORD=%DB_PASSWORD%
psql -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d postgres -c "SELECT 1" >nul 2>&1
if %errorlevel% neq 0 (
    echo ❌ PostgreSQL is not running on %DB_HOST%:%DB_PORT%
    echo.
    echo Please start PostgreSQL:
    echo   net start postgresql-x64-14
    echo   or check Services (services.msc) for PostgreSQL service
    echo.
    pause
    exit /b 1
)
echo ✅ PostgreSQL is running
echo.

REM Step 4: Check if database exists
echo Step 4: Checking if database exists...
psql -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d postgres -lqt 2>nul | findstr /C:"%DB_NAME%" >nul
if %errorlevel% equ 0 (
    echo ⚠️  Database '%DB_NAME%' already exists
    set /p DROP_DB="Do you want to drop and recreate it? (y/N): "
    if /i "!DROP_DB!"=="y" (
        echo Dropping database '%DB_NAME%'...
        psql -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d postgres -c "DROP DATABASE IF EXISTS %DB_NAME%;" >nul 2>&1
        echo ✅ Database dropped
    ) else (
        echo Using existing database
    )
)
echo.

REM Step 5: Create database
echo Step 5: Creating database '%DB_NAME%'...
psql -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d postgres -lqt 2>nul | findstr /C:"%DB_NAME%" >nul
if %errorlevel% neq 0 (
    psql -h %DB_HOST% -p %DB_PORT% -U %DB_USER% -d postgres -c "CREATE DATABASE %DB_NAME%;" >nul 2>&1
    if %errorlevel% equ 0 (
        echo ✅ Database created successfully
    ) else (
        echo ❌ Failed to create database
        pause
        exit /b 1
    )
) else (
    echo ✅ Database already exists
)
echo.

REM Step 6: Push Prisma schema
echo Step 6: Pushing Prisma schema to database...
set DATABASE_URL=%DATABASE_URL%
call npx prisma db push --skip-generate >nul 2>&1
if %errorlevel% equ 0 (
    echo ✅ Prisma schema pushed successfully
) else (
    echo ❌ Failed to push Prisma schema
    pause
    exit /b 1
)
echo.

REM Step 7: Generate Prisma Client
echo Step 7: Generating Prisma Client...
call npx prisma generate >nul 2>&1
if %errorlevel% equ 0 (
    echo ✅ Prisma Client generated successfully
) else (
    echo ❌ Failed to generate Prisma Client
    pause
    exit /b 1
)
echo.

REM Step 8: Seed test data (optional)
echo Step 8: Seeding test data (optional)...
if exist "prisma\seed-basic.ts" (
    set DATABASE_URL=%DATABASE_URL%
    call npm run db:seed:basic >nul 2>&1
    if %errorlevel% equ 0 (
        echo ✅ Test data seeded successfully
    ) else (
        echo ⚠️  Seeding failed (optional step)
    )
) else (
    echo ⚠️  No seed script found (skipping)
)
echo.

REM Step 9: Create .env.test file
echo Step 9: Creating .env.test configuration...
(
echo # Test Database Configuration
echo # Generated by setup-test-db.bat
echo # %date% %time%
echo.
echo DATABASE_URL="%DATABASE_URL%"
echo.
echo # Test environment settings
echo NODE_ENV="test"
echo SKIP_INTEGRATION_TESTS="false"
echo.
echo # Auth settings (test^)
echo NEXTAUTH_SECRET="divine-test-secret-for-quantum-authentication-%random%"
echo NEXTAUTH_URL="http://localhost:3000"
echo.
echo # Payment provider test keys
echo PAYPAL_CLIENT_ID="test-paypal-client-id"
echo PAYPAL_CLIENT_SECRET="test-paypal-client-secret"
echo STRIPE_SECRET_KEY="test-stripe-secret-key"
echo STRIPE_PUBLISHABLE_KEY="test-stripe-publishable-key"
) > .env.test
echo ✅ Created .env.test file
echo.

REM Success message
echo.
echo ============================================================
echo   🎉 Test Database Setup Complete!
echo ============================================================
echo.
echo Your test database is ready for integration tests.
echo.
echo Test Database URL:
echo   %DATABASE_URL%
echo.
echo To run integration tests:
echo   npm run test:integration
echo.
echo To run all tests:
echo   npm test
echo.
echo To use .env.test for tests:
echo   set DATABASE_URL=%DATABASE_URL%
echo   npm run test:integration
echo.
echo Or add to your environment variables permanently:
echo   setx DATABASE_URL "%DATABASE_URL%"
echo.

endlocal
pause
